2021-10-31 22:15:20.571 [error] <0.350.0> Supervisor 'Elixir.DataPipeline.Supervisor' had child 'Elixir.DataPipeline.Consumer' started with 'Elixir.DataPipeline.Consumer':start_link([]) at undefined exit with reason {'EXIT',{undef,[{'Elixir.DataPipeline.Consumer',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1242}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,...}]}} in context start_error
2021-10-31 22:15:20.571 [error] <0.348.0> CRASH REPORT Process <0.348.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.DataPipeline.Consumer',{'EXIT',{undef,[{'Elixir.DataPipeline.Consumer',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,414}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,384}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1242}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]},{gen_server,init_it,...},...]}}}},...} in application_master:init/4 line 142
2021-10-31 22:19:39.720 [error] <0.354.0>@Elixir.Producer:init Supervisor 'Elixir.Consumer.Broadway.ProducerSupervisor' had child 'Elixir.Consumer.Broadway.Producer_0' started with 'Elixir.Broadway.Topology.ProducerStage':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.Consumer.Broadway.Producer_0'},{hibernate_after,15000}]) at undefined exit with reason call to undefined function 'Elixir.Producer':init([{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...]) in context start_error
2021-10-31 22:19:39.720 [error] <0.352.0> Supervisor 'Elixir.Consumer.Broadway.Supervisor' had child #Ref<0.393057305.3862953985.76038> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.Consumer.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Topology.ProducerStage',...}}], [{name,'Elixir.Consumer.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,2},{max_seconds,...}]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Consumer.Broadway.Producer_0',{undef,[{'Elixir.Producer',init,[[{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,100},{max_seconds,5},{max_restarts,3},{shutdown,30000},{name,'Elixir.Consumer'},{producer,[{hibernate_after,15000},{module,{'Elixir.Producer',[{queue,<<"test_queue">>}]}},{transformer,{'Elixir.DataPipeline.Consumer',transform,[]}},{concurrency,1},{rate_limiting,[{allowed_messages,...},...]}]},...]},...]],...},...]}}} in context start_error
2021-10-31 22:19:39.720 [error] <0.351.0>@Elixir.Broadway.Topology:init:37 CRASH REPORT Process <0.351.0> with 0 neighbours crashed with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,#Ref<0.393057305.3862953985.76038>,{shutdown,{failed_to_start_child,'Elixir.Consumer.Broadway.Producer_0',{undef,[{'Elixir.Producer',init,[[{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,100},{max_seconds,5},{max_restarts,3},{shutdown,30000},{name,'Elixir.Consumer'},{producer,[{hibernate_after,15000},{module,{'Elixir.Producer',[{queue,<<"test_queue">>}]}},{transformer,{'Elixir.DataPipeline.Consumer',...}},...]},...]},...]],...},...]}}}}}} in 'Elixir.Broadway.Topology':init/1 line 37
2021-10-31 22:19:39.721 [error] <0.350.0>@Elixir.Broadway.Topology:init:37 Supervisor 'Elixir.DataPipeline.Supervisor' had child 'Elixir.DataPipeline.Consumer' started with 'Elixir.DataPipeline.Consumer':start_link([]) at undefined exit with reason no match of right hand value {error,{shutdown,{failed_to_start_child,#Ref<0.393057305.3862953985.76038>,{shutdown,{failed_to_start_child,'Elixir.Consumer.Broadway.Producer_0',{undef,[{'Elixir.Producer',init,[[{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,100},{max_seconds,5},{max_restarts,3},{shutdown,30000},{name,'Elixir.Consumer'},{producer,[{hibernate_after,15000},{module,{'Elixir.Producer',[{queue,<<"test_queue">>}]}},{transformer,{'Elixir.DataPipeline.Consumer',...}},...]},...]},...]],...},...]}}}}}} in 'Elixir.Broadway.Topology':init/1 line 37 in context start_error
2021-10-31 22:19:39.721 [error] <0.348.0> CRASH REPORT Process <0.348.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.DataPipeline.Consumer',{{badmatch,{error,{shutdown,{failed_to_start_child,#Ref<0.393057305.3862953985.76038>,{shutdown,{failed_to_start_child,'Elixir.Consumer.Broadway.Producer_0',{undef,[{'Elixir.Producer',init,[[{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,100},{max_seconds,5},{max_restarts,3},{shutdown,30000},{name,'Elixir.Consumer'},{producer,[{hibernate_after,15000},{module,{'Elixir.Producer',...}},...]},...]},...]],...},...]}}}}}}},...}}},...} in application_master:init/4 line 142
2021-10-31 22:21:45.942 [error] <0.354.0>@Elixir.DataPipeline.Producer:init Supervisor 'Elixir.DataPipeline.Consumer.Broadway.ProducerSupervisor' had child 'Elixir.DataPipeline.Consumer.Broadway.Producer_0' started with 'Elixir.Broadway.Topology.ProducerStage':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.DataPipeline.Consumer.Broadway.Producer_0'},{hibernate_after,15000}]) at undefined exit with reason call to undefined function 'Elixir.DataPipeline.Producer':init([{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...]) in context start_error
2021-10-31 22:21:45.943 [error] <0.352.0> Supervisor 'Elixir.DataPipeline.Consumer.Broadway.Supervisor' had child #Ref<0.1018639249.3326607366.119273> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.DataPipeline.Consumer.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Topology.ProducerStage',...}}], [{name,'Elixir.DataPipeline.Consumer.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.DataPipeline.Consumer.Broadway.Producer_0',{undef,[{'Elixir.DataPipeline.Producer',init,[[{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,100},{max_seconds,5},{max_restarts,3},{shutdown,30000},{name,'Elixir.DataPipeline.Consumer'},{producer,[{hibernate_after,15000},{module,{'Elixir.DataPipeline.Producer',[{queue,<<"test_queue">>}]}},{transformer,{'Elixir.DataPipeline.Consumer',transform,[]}},...]},...]},...]],...},...]}}} in context start_error
2021-10-31 22:21:45.943 [error] <0.351.0>@Elixir.Broadway.Topology:init:37 CRASH REPORT Process <0.351.0> with 0 neighbours crashed with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,#Ref<0.1018639249.3326607366.119273>,{shutdown,{failed_to_start_child,'Elixir.DataPipeline.Consumer.Broadway.Producer_0',{undef,[{'Elixir.DataPipeline.Producer',init,[[{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,100},{max_seconds,5},{max_restarts,3},{shutdown,30000},{name,'Elixir.DataPipeline.Consumer'},{producer,[{hibernate_after,15000},{module,{'Elixir.DataPipeline.Producer',[{queue,<<"...">>}]}},...]},...]},...]],...},...]}}}}}} in 'Elixir.Broadway.Topology':init/1 line 37
2021-10-31 22:21:45.943 [error] <0.350.0>@Elixir.Broadway.Topology:init:37 Supervisor 'Elixir.DataPipeline.Supervisor' had child 'Elixir.DataPipeline.Consumer' started with 'Elixir.DataPipeline.Consumer':start_link([]) at undefined exit with reason no match of right hand value {error,{shutdown,{failed_to_start_child,#Ref<0.1018639249.3326607366.119273>,{shutdown,{failed_to_start_child,'Elixir.DataPipeline.Consumer.Broadway.Producer_0',{undef,[{'Elixir.DataPipeline.Producer',init,[[{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,100},{max_seconds,5},{max_restarts,3},{shutdown,30000},{name,'Elixir.DataPipeline.Consumer'},{producer,[{hibernate_after,15000},{module,{'Elixir.DataPipeline.Producer',[{queue,<<"...">>}]}},...]},...]},...]],...},...]}}}}}} in 'Elixir.Broadway.Topology':init/1 line 37 in context start_error
2021-10-31 22:21:45.943 [error] <0.348.0> CRASH REPORT Process <0.348.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.DataPipeline.Consumer',{{badmatch,{error,{shutdown,{failed_to_start_child,#Ref<0.1018639249.3326607366.119273>,{shutdown,{failed_to_start_child,'Elixir.DataPipeline.Consumer.Broadway.Producer_0',{undef,[{'Elixir.DataPipeline.Producer',init,[[{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,100},{max_seconds,5},{max_restarts,3},{shutdown,30000},{name,'Elixir.DataPipeline.Consumer'},{producer,...},...]},...]],...},...]}}}}}}},...}}},...} in application_master:init/4 line 142
2021-10-31 22:25:04.319 [error] <0.354.0>@Elixir.DataPipeline.Producer:init Supervisor 'Elixir.DataPipeline.Consumer.Broadway.ProducerSupervisor' had child 'Elixir.DataPipeline.Consumer.Broadway.Producer_0' started with 'Elixir.Broadway.Topology.ProducerStage':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.DataPipeline.Consumer.Broadway.Producer_0'},{hibernate_after,15000}]) at undefined exit with reason call to undefined function 'Elixir.DataPipeline.Producer':init([{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...]) in context start_error
2021-10-31 22:25:04.319 [error] <0.352.0> Supervisor 'Elixir.DataPipeline.Consumer.Broadway.Supervisor' had child #Ref<0.101151565.643039235.218309> started with 'Elixir.Supervisor':start_link([#{id => 'Elixir.DataPipeline.Consumer.Broadway.Producer_0',shutdown => 30000,start => {'Elixir.Broadway.Topology.ProducerStage',...}}], [{name,'Elixir.DataPipeline.Consumer.Broadway.ProducerSupervisor'},{strategy,one_for_one},{max_restarts,...},...]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.DataPipeline.Consumer.Broadway.Producer_0',{undef,[{'Elixir.DataPipeline.Producer',init,[[{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,100},{max_seconds,5},{max_restarts,3},{shutdown,30000},{name,'Elixir.DataPipeline.Consumer'},{producer,[{hibernate_after,15000},{module,{'Elixir.DataPipeline.Producer',[{queue,<<"test_queue">>}]}},{transformer,{'Elixir.DataPipeline.Consumer',transform,[]}},...]},...]},...]],...},...]}}} in context start_error
2021-10-31 22:25:04.319 [error] <0.351.0>@Elixir.Broadway.Topology:init:37 CRASH REPORT Process <0.351.0> with 0 neighbours crashed with reason: no match of right hand value {error,{shutdown,{failed_to_start_child,#Ref<0.101151565.643039235.218309>,{shutdown,{failed_to_start_child,'Elixir.DataPipeline.Consumer.Broadway.Producer_0',{undef,[{'Elixir.DataPipeline.Producer',init,[[{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,100},{max_seconds,5},{max_restarts,3},{shutdown,30000},{name,'Elixir.DataPipeline.Consumer'},{producer,[{hibernate_after,15000},{module,{'Elixir.DataPipeline.Producer',[{queue,<<"te...">>}]}},...]},...]},...]],...},...]}}}}}} in 'Elixir.Broadway.Topology':init/1 line 37
2021-10-31 22:25:04.319 [error] <0.350.0>@Elixir.Broadway.Topology:init:37 Supervisor 'Elixir.DataPipeline.Supervisor' had child 'Elixir.DataPipeline.Consumer' started with 'Elixir.DataPipeline.Consumer':start_link([]) at undefined exit with reason no match of right hand value {error,{shutdown,{failed_to_start_child,#Ref<0.101151565.643039235.218309>,{shutdown,{failed_to_start_child,'Elixir.DataPipeline.Consumer.Broadway.Producer_0',{undef,[{'Elixir.DataPipeline.Producer',init,[[{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,100},{max_seconds,5},{max_restarts,3},{shutdown,30000},{name,'Elixir.DataPipeline.Consumer'},{producer,[{hibernate_after,15000},{module,{'Elixir.DataPipeline.Producer',[{queue,<<"te...">>}]}},...]},...]},...]],...},...]}}}}}} in 'Elixir.Broadway.Topology':init/1 line 37 in context start_error
2021-10-31 22:25:04.320 [error] <0.348.0> CRASH REPORT Process <0.348.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.DataPipeline.Consumer',{{badmatch,{error,{shutdown,{failed_to_start_child,#Ref<0.101151565.643039235.218309>,{shutdown,{failed_to_start_child,'Elixir.DataPipeline.Consumer.Broadway.Producer_0',{undef,[{'Elixir.DataPipeline.Producer',init,[[{broadway,[{index,0},{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,100},{max_seconds,5},{max_restarts,3},{shutdown,30000},{name,'Elixir.DataPipeline.Consumer'},{producer,...},...]},...]],...},...]}}}}}}},...}}},...} in application_master:init/4 line 142
